#.github/workflows/react_deploy.yml
name: CD Stage
on:
  push: 
    branches:
      - qa
      - '!master'
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up nodejs 14 LTS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2.0.0
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.cache-name }}-
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Install npm dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd frontend && npm install
      - name: ‚õè Building
        run: cd frontend && npm run build --if-present
      - name: Deploy to QA Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: "-rltgoDzvO --delete"
            SOURCE: "frontend/dist/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
            EXCLUDE: "/node_modules/"
